# Generated by Django 2.2.16 on 2022-11-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
    ]
